DROP TABLE IF EXISTS TASK;
CREATE TABLE TASK (ID INT PRIMARY KEY, TASK_NAME VARCHAR(50));

INSERT INTO TASK (ID, TASK_NAME) VALUES (1, 'Task1');
INSERT INTO TASK (ID, TASK_NAME) VALUES (2, 'Task2');
INSERT INTO TASK (ID, TASK_NAME) VALUES (3, 'Task3');
INSERT INTO TASK (ID, TASK_NAME) VALUES (4, 'Task4');
INSERT INTO TASK (ID, TASK_NAME) VALUES (5, 'Task5');